---
openapi: 3.0.0
info:
   version: 1.3.0
   title: dynamicapp open api specification
   description: addfile API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8016
     description: addfile
tags:
- name: files
paths:
   "/files":
      post:
         tags:
         -  files
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/files"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/files/userid/created_by":
      get:
         tags:
         -  files
         description: GpGetNounCreatedBy
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      files:
         type: object
         properties:
            name:
               type: "string"
               description: Description