---
openapi: 3.0.0
info:
   version: 1.3.0
   title: dynamicapp open api specification
   description: listdrop API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8020
     description: listdrop
tags:
- name: listdrop
paths:
   "/listdrop":
      get:
         tags:
         -  listdrop
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  listdrop
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/listdrop"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/listdrop/userid/created_by":
      get:
         tags:
         -  listdrop
         description: GpGetNounCreatedBy
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      listdrop:
         type: object
         properties:
            name:
               type: "string"
               description: Description
            files:
               type: "string"
               description: Description